### ISSUE TITLE
Installation with Basic controller

### ISSUE THREAD

**Issue by bskram** [wesleywh/InvectorPhotonPUNMultiplayerAddon#2]
Should this script support Basic Controller, or do I need to install the shooter or melee to get it to work? I have an issue with the camera not following the 2nd player. (And the input script is by default disabled).

**Comment by wesleywh** [comment]
These editor scripts do not support the basic controller. This was written
specifically with the shooter template in mind. There are a few versions
that work with the melee template on github but they are older (I should
really just jump back in to convert this to work with the melee template).
The reason the controller script is disabled by default is because the
network controller has to verify that it is you that owns that spawned
player. Otherwise you get issues with being able to control other player
objects that are not your own.

**Comment by wesleywh** [comment]
Did you get this to work?

Looks like the last back port that I did for melee only was for version 2.0

**Comment by wesleywh** [comment]
What's the word on this?

**Comment by wesleywh** [comment]
Closing since I haven't heard anything.
